// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.17.3
// source: healthcheck.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthcheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckRequest) Reset() {
	*x = HealthcheckRequest{}
	mi := &file_healthcheck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckRequest) ProtoMessage() {}

func (x *HealthcheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_healthcheck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckRequest.ProtoReflect.Descriptor instead.
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return file_healthcheck_proto_rawDescGZIP(), []int{0}
}

type HealthcheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckResponse) Reset() {
	*x = HealthcheckResponse{}
	mi := &file_healthcheck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckResponse) ProtoMessage() {}

func (x *HealthcheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_healthcheck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckResponse.ProtoReflect.Descriptor instead.
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return file_healthcheck_proto_rawDescGZIP(), []int{1}
}

func (x *HealthcheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_healthcheck_proto protoreflect.FileDescriptor

const file_healthcheck_proto_rawDesc = "" +
	"\n" +
	"\x11healthcheck.proto\x12\x02pb\"\x14\n" +
	"\x12HealthcheckRequest\"/\n" +
	"\x13HealthcheckResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2V\n" +
	"\x12HealthcheckService\x12@\n" +
	"\vHealthcheck\x12\x16.pb.HealthcheckRequest\x1a\x17.pb.HealthcheckResponse\"\x00B\x1eZ\x1cgithub.com/crazy-max/diun/pbb\x06proto3"

var (
	file_healthcheck_proto_rawDescOnce sync.Once
	file_healthcheck_proto_rawDescData []byte
)

func file_healthcheck_proto_rawDescGZIP() []byte {
	file_healthcheck_proto_rawDescOnce.Do(func() {
		file_healthcheck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_healthcheck_proto_rawDesc), len(file_healthcheck_proto_rawDesc)))
	})
	return file_healthcheck_proto_rawDescData
}

var file_healthcheck_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_healthcheck_proto_goTypes = []any{
	(*HealthcheckRequest)(nil),  // 0: pb.HealthcheckRequest
	(*HealthcheckResponse)(nil), // 1: pb.HealthcheckResponse
}
var file_healthcheck_proto_depIdxs = []int32{
	0, // 0: pb.HealthcheckService.Healthcheck:input_type -> pb.HealthcheckRequest
	1, // 1: pb.HealthcheckService.Healthcheck:output_type -> pb.HealthcheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_healthcheck_proto_init() }
func file_healthcheck_proto_init() {
	if File_healthcheck_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_healthcheck_proto_rawDesc), len(file_healthcheck_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_healthcheck_proto_goTypes,
		DependencyIndexes: file_healthcheck_proto_depIdxs,
		MessageInfos:      file_healthcheck_proto_msgTypes,
	}.Build()
	File_healthcheck_proto = out.File
	file_healthcheck_proto_goTypes = nil
	file_healthcheck_proto_depIdxs = nil
}
