// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.17.3
// source: image.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Digest        string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Platform      string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Manifest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Manifest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Manifest) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Manifest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Manifest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Manifest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ImageListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageListRequest) Reset() {
	*x = ImageListRequest{}
	mi := &file_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListRequest) ProtoMessage() {}

func (x *ImageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageListRequest.ProtoReflect.Descriptor instead.
func (*ImageListRequest) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{1}
}

type ImageListResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Images        []*ImageListResponse_Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageListResponse) Reset() {
	*x = ImageListResponse{}
	mi := &file_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListResponse) ProtoMessage() {}

func (x *ImageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageListResponse.ProtoReflect.Descriptor instead.
func (*ImageListResponse) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{2}
}

func (x *ImageListResponse) GetImages() []*ImageListResponse_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type ImageInspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInspectRequest) Reset() {
	*x = ImageInspectRequest{}
	mi := &file_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInspectRequest) ProtoMessage() {}

func (x *ImageInspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInspectRequest.ProtoReflect.Descriptor instead.
func (*ImageInspectRequest) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{3}
}

func (x *ImageInspectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ImageInspectResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Image         *ImageInspectResponse_Image `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInspectResponse) Reset() {
	*x = ImageInspectResponse{}
	mi := &file_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInspectResponse) ProtoMessage() {}

func (x *ImageInspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInspectResponse.ProtoReflect.Descriptor instead.
func (*ImageInspectResponse) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{4}
}

func (x *ImageInspectResponse) GetImage() *ImageInspectResponse_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type ImageRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRemoveRequest) Reset() {
	*x = ImageRemoveRequest{}
	mi := &file_image_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRemoveRequest) ProtoMessage() {}

func (x *ImageRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRemoveRequest.ProtoReflect.Descriptor instead.
func (*ImageRemoveRequest) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{5}
}

func (x *ImageRemoveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ImageRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifests     []*Manifest            `protobuf:"bytes,1,rep,name=manifests,proto3" json:"manifests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRemoveResponse) Reset() {
	*x = ImageRemoveResponse{}
	mi := &file_image_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRemoveResponse) ProtoMessage() {}

func (x *ImageRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRemoveResponse.ProtoReflect.Descriptor instead.
func (*ImageRemoveResponse) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{6}
}

func (x *ImageRemoveResponse) GetManifests() []*Manifest {
	if x != nil {
		return x.Manifests
	}
	return nil
}

type ImagePruneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	Filter        string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePruneRequest) Reset() {
	*x = ImagePruneRequest{}
	mi := &file_image_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePruneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePruneRequest) ProtoMessage() {}

func (x *ImagePruneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePruneRequest.ProtoReflect.Descriptor instead.
func (*ImagePruneRequest) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{7}
}

func (x *ImagePruneRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *ImagePruneRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ImagePruneResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Images        []*ImagePruneResponse_Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePruneResponse) Reset() {
	*x = ImagePruneResponse{}
	mi := &file_image_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePruneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePruneResponse) ProtoMessage() {}

func (x *ImagePruneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePruneResponse.ProtoReflect.Descriptor instead.
func (*ImagePruneResponse) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{8}
}

func (x *ImagePruneResponse) GetImages() []*ImagePruneResponse_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type ImageListResponse_Image struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ManifestsCount int64                  `protobuf:"varint,2,opt,name=manifestsCount,proto3" json:"manifestsCount,omitempty"`
	Latest         *Manifest              `protobuf:"bytes,3,opt,name=latest,proto3" json:"latest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImageListResponse_Image) Reset() {
	*x = ImageListResponse_Image{}
	mi := &file_image_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageListResponse_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListResponse_Image) ProtoMessage() {}

func (x *ImageListResponse_Image) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageListResponse_Image.ProtoReflect.Descriptor instead.
func (*ImageListResponse_Image) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ImageListResponse_Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageListResponse_Image) GetManifestsCount() int64 {
	if x != nil {
		return x.ManifestsCount
	}
	return 0
}

func (x *ImageListResponse_Image) GetLatest() *Manifest {
	if x != nil {
		return x.Latest
	}
	return nil
}

type ImageInspectResponse_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Manifests     []*Manifest            `protobuf:"bytes,2,rep,name=manifests,proto3" json:"manifests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInspectResponse_Image) Reset() {
	*x = ImageInspectResponse_Image{}
	mi := &file_image_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInspectResponse_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInspectResponse_Image) ProtoMessage() {}

func (x *ImageInspectResponse_Image) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInspectResponse_Image.ProtoReflect.Descriptor instead.
func (*ImageInspectResponse_Image) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ImageInspectResponse_Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageInspectResponse_Image) GetManifests() []*Manifest {
	if x != nil {
		return x.Manifests
	}
	return nil
}

type ImagePruneResponse_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Manifests     []*Manifest            `protobuf:"bytes,2,rep,name=manifests,proto3" json:"manifests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePruneResponse_Image) Reset() {
	*x = ImagePruneResponse_Image{}
	mi := &file_image_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePruneResponse_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePruneResponse_Image) ProtoMessage() {}

func (x *ImagePruneResponse_Image) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePruneResponse_Image.ProtoReflect.Descriptor instead.
func (*ImagePruneResponse_Image) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ImagePruneResponse_Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImagePruneResponse_Image) GetManifests() []*Manifest {
	if x != nil {
		return x.Manifests
	}
	return nil
}

var File_image_proto protoreflect.FileDescriptor

const file_image_proto_rawDesc = "" +
	"\n" +
	"\vimage.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x02\n" +
	"\bManifest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x124\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x120\n" +
	"\x06labels\x18\x05 \x03(\v2\x18.pb.Manifest.LabelsEntryR\x06labels\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x12\n" +
	"\x10ImageListRequest\"\xb3\x01\n" +
	"\x11ImageListResponse\x123\n" +
	"\x06images\x18\x01 \x03(\v2\x1b.pb.ImageListResponse.ImageR\x06images\x1ai\n" +
	"\x05Image\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x0emanifestsCount\x18\x02 \x01(\x03R\x0emanifestsCount\x12$\n" +
	"\x06latest\x18\x03 \x01(\v2\f.pb.ManifestR\x06latest\")\n" +
	"\x13ImageInspectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x95\x01\n" +
	"\x14ImageInspectResponse\x124\n" +
	"\x05image\x18\x01 \x01(\v2\x1e.pb.ImageInspectResponse.ImageR\x05image\x1aG\n" +
	"\x05Image\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\tmanifests\x18\x02 \x03(\v2\f.pb.ManifestR\tmanifests\"(\n" +
	"\x12ImageRemoveRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"A\n" +
	"\x13ImageRemoveResponse\x12*\n" +
	"\tmanifests\x18\x01 \x03(\v2\f.pb.ManifestR\tmanifests\"=\n" +
	"\x11ImagePruneRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\"\x93\x01\n" +
	"\x12ImagePruneResponse\x124\n" +
	"\x06images\x18\x01 \x03(\v2\x1c.pb.ImagePruneResponse.ImageR\x06images\x1aG\n" +
	"\x05Image\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\tmanifests\x18\x02 \x03(\v2\f.pb.ManifestR\tmanifests2\x90\x02\n" +
	"\fImageService\x12:\n" +
	"\tImageList\x12\x14.pb.ImageListRequest\x1a\x15.pb.ImageListResponse\"\x00\x12C\n" +
	"\fImageInspect\x12\x17.pb.ImageInspectRequest\x1a\x18.pb.ImageInspectResponse\"\x00\x12@\n" +
	"\vImageRemove\x12\x16.pb.ImageRemoveRequest\x1a\x17.pb.ImageRemoveResponse\"\x00\x12=\n" +
	"\n" +
	"ImagePrune\x12\x15.pb.ImagePruneRequest\x1a\x16.pb.ImagePruneResponse\"\x00B\x1eZ\x1cgithub.com/crazy-max/diun/pbb\x06proto3"

var (
	file_image_proto_rawDescOnce sync.Once
	file_image_proto_rawDescData []byte
)

func file_image_proto_rawDescGZIP() []byte {
	file_image_proto_rawDescOnce.Do(func() {
		file_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_image_proto_rawDesc), len(file_image_proto_rawDesc)))
	})
	return file_image_proto_rawDescData
}

var file_image_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_image_proto_goTypes = []any{
	(*Manifest)(nil),                   // 0: pb.Manifest
	(*ImageListRequest)(nil),           // 1: pb.ImageListRequest
	(*ImageListResponse)(nil),          // 2: pb.ImageListResponse
	(*ImageInspectRequest)(nil),        // 3: pb.ImageInspectRequest
	(*ImageInspectResponse)(nil),       // 4: pb.ImageInspectResponse
	(*ImageRemoveRequest)(nil),         // 5: pb.ImageRemoveRequest
	(*ImageRemoveResponse)(nil),        // 6: pb.ImageRemoveResponse
	(*ImagePruneRequest)(nil),          // 7: pb.ImagePruneRequest
	(*ImagePruneResponse)(nil),         // 8: pb.ImagePruneResponse
	nil,                                // 9: pb.Manifest.LabelsEntry
	(*ImageListResponse_Image)(nil),    // 10: pb.ImageListResponse.Image
	(*ImageInspectResponse_Image)(nil), // 11: pb.ImageInspectResponse.Image
	(*ImagePruneResponse_Image)(nil),   // 12: pb.ImagePruneResponse.Image
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
}
var file_image_proto_depIdxs = []int32{
	13, // 0: pb.Manifest.created:type_name -> google.protobuf.Timestamp
	9,  // 1: pb.Manifest.labels:type_name -> pb.Manifest.LabelsEntry
	10, // 2: pb.ImageListResponse.images:type_name -> pb.ImageListResponse.Image
	11, // 3: pb.ImageInspectResponse.image:type_name -> pb.ImageInspectResponse.Image
	0,  // 4: pb.ImageRemoveResponse.manifests:type_name -> pb.Manifest
	12, // 5: pb.ImagePruneResponse.images:type_name -> pb.ImagePruneResponse.Image
	0,  // 6: pb.ImageListResponse.Image.latest:type_name -> pb.Manifest
	0,  // 7: pb.ImageInspectResponse.Image.manifests:type_name -> pb.Manifest
	0,  // 8: pb.ImagePruneResponse.Image.manifests:type_name -> pb.Manifest
	1,  // 9: pb.ImageService.ImageList:input_type -> pb.ImageListRequest
	3,  // 10: pb.ImageService.ImageInspect:input_type -> pb.ImageInspectRequest
	5,  // 11: pb.ImageService.ImageRemove:input_type -> pb.ImageRemoveRequest
	7,  // 12: pb.ImageService.ImagePrune:input_type -> pb.ImagePruneRequest
	2,  // 13: pb.ImageService.ImageList:output_type -> pb.ImageListResponse
	4,  // 14: pb.ImageService.ImageInspect:output_type -> pb.ImageInspectResponse
	6,  // 15: pb.ImageService.ImageRemove:output_type -> pb.ImageRemoveResponse
	8,  // 16: pb.ImageService.ImagePrune:output_type -> pb.ImagePruneResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_image_proto_init() }
func file_image_proto_init() {
	if File_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_image_proto_rawDesc), len(file_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_proto_goTypes,
		DependencyIndexes: file_image_proto_depIdxs,
		MessageInfos:      file_image_proto_msgTypes,
	}.Build()
	File_image_proto = out.File
	file_image_proto_goTypes = nil
	file_image_proto_depIdxs = nil
}
