name: docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:

env:
  DESTDIR: ./bin
  DOCKER_BUILD_SUMMARY: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to push to gh-pages
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      -
        name: Build docs
        uses: docker/bake-action@a66e1c87e2eca0503c343edf1d208c716d54b8a8 # v7.1.0
        with:
          source: .
          provenance: false
          targets: docs
      -
        name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@f0ef9e1cf727f9f76f8485f8c525fa03afc4ec02 # v5.0.0
        with:
          pages_threshold: major_outage
      -
        name: Deploy
        if: github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@1d6ee9b181a81033a16bd707a1401afa978daab4 # v5.0.0
        with:
          target_branch: gh-pages
          build_dir: ${{ env.DESTDIR }}/site
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
